name = "voipapp"
main = "src/index.js"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "voipapp-production"
database_id = "717d56b5-8525-8800-fca3-843fead6"
